<?php
$this->breadcrumbs=array(
	'TESTIMONIALS',
);
$this->pageTitle = 'Resources of Startup Jobs Asia | '.Yii::app()->params['pageTitle'];
?>



<div class="row-fluid">
<div class="span9">
		<div class="clear">
			<h1 class="Advisors">Terms and Conditions</h1>
		</div>


This website of Startup Jobs Asia Pte Ltd ("<strong>Company</strong>") and any other site of the Company accessed through this website: http://www.startupjobs.asia (collectively "<strong>Website</strong>") and the services provided therein shall only be available to users seeking employment ("<strong>Jobseeker(s)</strong>"), users seeking employees ("<strong>Employer(s)</strong>") and other users such as advertisers. Access to and use of the contents and services provided on the Website shall be subject to the Privacy Statement and the Terms and Conditions (which are set out below). If you do not accept either or both of the <strong>Privacy Statement</strong> and/or the <strong>Terms and Conditions</strong>, please do not use the Website. Upon your acceptance of the <strong>Privacy Statement</strong> and the <strong>Terms and Conditions</strong>, the Terms and Conditions shall be bindin upon you. The Company may revise the <strong>Privacy Statement</strong> and the <strong>Terms and Conditions</strong> at any time without prior notice. You are advised to periodically review the <strong>Privacy Statement</strong> and the <strong>Terms and Conditions</strong>. Your access to the Website and the Company's services will be terminated upon your notice to the Company that any change is unacceptable; otherwise your continued use shall constitute your acceptance of all changes and they shall be binding upon you. The terms "you", "user" and "users" herein refer to all individuals and/or entities accessing and/or using the Website at any time for any reason or purpose.

Please refer to the details of the Company's Privacy Statement by clicking on this <a href="http://www.startupjobs.asia/site/page/view/privacy-statement/">link</a>.
<h2><span style="text-decoration: underline;">1. Acceptable Website Uses</span></h2>
<div style="padding-left: 30px;">

<span style="text-decoration: underline;">a. Specific Uses - Jobseeker</span>
<div style="padding-left: 30px;">

Jobseeker agrees that he/she shall only use the Website for lawful purposes and seeking employment.

Jobseeker agrees to keep his/her login name and password with care and not to disclose them to any other person. Jobseeker is solely responsible for maintaining the confidentiality of such login name and password and shall notify the Company immediately of any unauthorized use of the same.

Jobseeker confirms and acknowledges that he/she discloses his/her personal data to the Employers and/or the Company of his/her own volition when he/she applies for available job vacancies posted on or through the Website, and/or when Jobseeker uses the Website for purposes of submitting, uploading or posting his/her resume on the Website. By submitting, uploading or posting his/her resume on the Website, Jobseeker authorizes the Company to store his/her resume and information or data related thereto in the database of the Company ("<strong>Database</strong>"). Jobseeker may send his/her resume and the related information or data directly to any Employer who advertises on or through the Website. Alternatively, Jobseeker may send his/her resume and the related information or data to the Company through the website in reply to any job advertisement. In such event, Jobseeker's resume and the related information or data will remain active on the Website and be stored in the Database at his/her own risk unless and until he/she chooses to delete them. Jobseeker acknowledges and agrees that his/her resume and the related information or data may be accessed by the Employers who have subscribed to the services of the Company, for the sole purpose of recruiting and assessing the suitability of Jobseekers. The Company also reserves the right to reject, disapprove or edit any Jobseeker's resume and information or data related thereto as it sees appropriate and to erase any personal data which the Company reasonably believes is inaccurate having regard to the purpose (including any directly related purpose) for which the data is or is to be used.

Jobseeker acknowledges and agrees to the Company's practice of charging Employer a fee for access to the Website, the Database and/or Jobseekers' resumes, details and information or data related thereto, for the sole purpose of recruiting and assessing the suitability of Jobseekers and subject to the terms herein. Jobseeker also recognizes that he/she shall have no claims to any such fee received by the Company.

The Company will not release Jobseeker's personal data to any Employer without his/her permission. Jobseeker acknowledges and agrees that the Company will, if he/she so authorizes, release his/her resume (without his/her personal and contact information and name of his/her current employer) to Employer through the use of the Company's search engine or any other means for the sole purpose of enabling Employer to recruit and assess the suitability of Jobseekers in relation to any job vacancy. Jobseeker agrees that the Company and its associated companies may use his/her personal data (without his/her name, address and other personal identifiable information) for marketing purposes which may be directed to either potential employers or Employers, their respective agents or anyone under their employ.

Although the Company shall use its reasonable endeavours to restrict access to the Database only to the Employers and personnel of the Company, it does not guarantee that other parties will not, without the Company's consent, gain access to the Database. Jobseeker may disable searching or viewing of his/her resume by the Employers at any time. However, Jobseeker acknowledges that the Employers and other parties who have otherwise gained access to the Database may have retained a copy of Jobseeker's resume. The Company is not responsible for the retention, use or privacy of resumes in these instances, or for the use or privacy of resumes by any of such parties while the resumes are in the Database.

The Company will not be responsible or held liable in any way if any Employer or other user, in breach of the Terms and Conditions, whether in Singapore or elsewhere, uses the Jobseeker's personal data, information or materials for any purpose other than for recruiting potential employees. Jobseeker accepts that all personal data, information or materials given to Employer or other users, or submitted on or through the Website, are given entirely at his/her own risk.

</div>
<span style="text-decoration: underline;">b. Specific Uses - Employer</span>
<div style="padding-left: 30px;">

Employer agrees that it shall only use the Website for lawful purposes and seeking potential employees.

Upon payment of the service fee to the Company or upon acceptance of any free trial promotion offer, Employer will be entitled to use the Website to advertise job vacancies and/or create its own web page on the Website for a predetermined period following agreement on the predetermined service. Subject to the conditions or requirements from time to time stipulated by the Company regarding access to Jobseeker's information or data, Employer will be entitled to access the Database but agrees that all information or data obtained as a result of such access shall only be used for the sole purpose of recruiting and assessing the suitability of Jobseekers and that such information or data shall not be disclosed to any other parties without the prior consent of the Jobseeker concerned. Employer acknowledges and agrees that it shall disregard any information or data received from Jobseeker which is irrelevant to recruiting and assessing the suitability of Jobseekers.

Employer shall be solely responsible for the contents of and materials contained in its advertisements and/or web page posted on the Website. The Company reserves the right to remove or edit, or require the removal or amendment of, any advertisement or web page as it sees appropriate, or to terminate or suspend the Employer's access and use of the Website and/or services offered on or through the Website, in accordance with the agreement for such services between Employer and the Company.

The Company shall have the right to terminate any services to any Employer and remove any advertisement and/or web page posted on the Website at the Company's sole discretion, without any compensation or recourse to Employer.

The Company also reserves the right to change the service fee or institute new charges or fees, as it deems appropriate. In the event that any Employer fails to pay the service fee or any other fees or charges due to the Company, the Company reserves the right to suspend or terminate the Employer's web page and/or advertisements and/or right to access the Database, without prejudice to all other rights and remedies available to the Company.

</div>
<span style="text-decoration: underline;">c. Prohibited Uses - Jobseekers and Employers</span>

Jobseeker and/or Employer agree(s) that: -
<div style="padding-left: 30px;">

Jobseeker shall not post any non-resume related information or data and/or incomplete, false or inaccurate resume related information or data on the Website.

Jobseeker shall not respond to any job vacancy advertisement for any reason other than to apply for the job advertised, and Employer shall not respond to any Jobseeker other than in connection with his/her application for a job. Any communications or use of the Website for any purposes other than recruitment purposes, including but not limited to soliciting of donations or business for any reason, are strictly prohibited.

All users shall not use the Website in any manner that infringes the intellectual property rights or proprietary rights of others.

All users shall not print, download, duplicate or otherwise copy, reproduce, re-distribute, republish or use any personally identifiable information about other users, except that Employers may use the Database and/or Jobseekers'
resumes and information or data related thereto pursuant to Clause 1.b. above. All unsolicited communications of any type to users are strictly prohibited.

All users shall not delete, revise or remove any material posted by any other person or entity.

All users are prohibited from violating or attempting to violate the security of the Website including, without limitation, accessing data not intended for them or logging into a server or account which they are not authorized to access, attempting to probe, scan or test the vulnerability of a system or network or attempting to breach security or authentication measures without proper authorization, attempting to interfere with service to any user, host or network or sending unsolicited e-mails, including e-mails containing promotions and/or advertisements for products or services. Violations of system or network security may result in civil and/or criminal liabilities, including under the Computer Misuse Act (Cap. 50A) and the Spam Control Act (Cap. 311A).

All users shall not upload, post, publish, transmit, distribute, circulate or store any material on or to the Website: (i) in violation of any applicable law or regulation; (ii) in any manner that may infringe the copyright, trademark, trade secrets or other intellectual property rights or proprietary rights of others or violate the privacy or publicity or other personal rights of others; (iii) that is harmful, defamatory, libelous, obscene, discriminatory, harassing, threatening, abusive, hateful, racist, political, religious, blasphemous, false, illegal, improper or is otherwise offensive or objectionable; or (iv) that contains viruses, trojan horses, worms, corrupted files or other materials or programs that may interrupt, damage or limit the functionality and operation of the Website, the services offered on the Website, or of any computer software or hardware or telecommunication equipment.

</div>
</div>
<h2><span style="text-decoration: underline;">2. Intellectual Property Rights</span></h2>
All contents of the Website, including without limitation information, text, graphics, images, layout, designs, pictures, logos, editorial content, HTML and other proprietary materials on the Website (collectively "Contents") are the intellectual property of the Company, its associated companies and/or licensors and are protected by copyright, trademark, patent and other intellectual property laws. Users acknowledge and agree that the Contents are made available solely for their personal non-commercial use. Except as otherwise provided in this paragraph, users shall not, and shall not procure, assist or facilitate any third party to, copy, reproduce, transmit, publish, disseminate, distribute, redistribute, broadcast, circulate, store (in any medium), display, modify, sell or transfer or participate in the sale or transfer of or offer for sale of, create derivative works from, or in any way exploit any of the Contents, whether in whole or in part. Users may download or copy the Contents solely for their personal non-commercial use and/or uses that are expressly permitted in these Terms and Conditions, provided that users will not delete or amend any symbols or statements in the Contents that indicate the subsistence therein of copyright, trademark and any other proprietary rights. Users do not obtain any right, title or interest in or to any or any part of the Contents as a result of such downloading or copying. The Company reserves all its rights of enforcement of all its intellectual property rights or proprietary rights in the Contents, including without limitation against any use of any of the Contents that is not expressly permitted under the Terms and Conditions. For the avoidance of doubt, any purported consent of any third parties (including Employers) to the use of the Contents or any part thereof shall not in any way exonerate the users from the restrictions/prohibitions imposed hereunder.
<h2><span style="text-decoration: underline;">3. Responsibility</span></h2>
The Company reserves the right to monitor the Website and its contents at all times, but is not obliged to do so. The Company takes no responsibility whatsoever for any material on the Website that is not posted by the Company or is otherwise posted by the Company on behalf of a user. All users acknowledge and agree that they are fully responsible for the form, content and accuracy of any resume, information, data, advertisement, web page and/or material submitted by them to the Company or that is otherwise posted by them on or through the Website. The Company does not warrant that any resume, advertisement or web page will be viewed by any specific number of users or that it will be viewed by any specific user or result in successful recruitment of personnel. The Company shall not in any way be considered an agent of either Employer or Jobseeker with respect to any use of the Website. The Company shall not be responsible in any way for any decision, for whatever reason, made by any party seeking or posting jobs on the Website, or of any party responding to or posting advertisements on the Website. <b>WHILST THE COMPANY HAS ENDEAVOURED TO PROVIDE A QUALITY SERVICE TO EMPLOYERS AND JOBSEEKERS, IT DOES NOT WARRANT THAT THE WEBSITE WILL OPERATE ERROR-FREE OR THAT THE WEBSITE AND ITS SERVER ARE FREE OF VIRUSES OR OTHER HARMFUL MECHANISMS, THAT ANY DEFECTS WILL BE CORRECTED, OR THAT THE OPERATION OF THE WEBSITE WILL BE UNINTERRUPTED, TIMELY OR SECURE. IF USE OF THE WEBSITE OR ITS CONTENTS RESULT IN THE NEED FOR SERVICING OR REPLACING EQUIPMENT OR DATA, BY ANY USER, THE COMPANY SHALL NOT BE RESPONSIBLE FOR THOSE COSTS AND ANY LOSS OR DAMAGE OF WHATSOEVER NATURE. THE WEBSITE AND ITS CONTENTS ARE PROVIDED ON AN "AS IS" BASIS WITHOUT ANY WARRANTIES OF ANY KIND. TO THE FULLEST EXTENT PERMITTED BY LAW, THE COMPANY DISCLAIMS ALL WARRANTIES, INCLUDING WITHOUT PREJUDICE TO THE FOREGOING, ANY WARRANTIES IN RESPECT OF MERCHANTABILITY, AVAILABILITY OF FEATURED PRODUCTS OR SERVICES, NON-INFRINGEMENT OF THIRD PARTY RIGHTS, FITNESS FOR PARTICULAR PURPOSE, OR ABOUT THE ACCURACY, RELIABILITY, COMPLETENESS, TIMELINESS OR OTHER QUALITIES OF THE WEBSITE AND THE CONTENTS, SERVICES, SOFTWARE, TEXT, GRAPHICS AND LINKS CONTAINED THEREIN.</b>
<h2><span style="text-decoration: underline;">4. Own Risk</span></h2>
<b>ALL USERS USE THE WEBSITE AND ANY OTHER WEBSITES ACCESSED THROUGH IT, ENTIRELY AT THEIR OWN RISK</b>. All users shall be responsible for their own communications and are responsible for the consequences of their activities on the Website. The Company does not represent or guarantee the truthfulness, accuracy or reliability of any of the communications posted by other users or endorse any opinions expressed by users. Any reliance by users on material posted by other users shall be at their own risk.
<h2><span style="text-decoration: underline;">5. Links to Other Sites</span></h2>
The Website may contain links to third-party websites. These are provided solely as a convenience to users and as Internet navigation tools, and not in any way as an endorsement by the Company of the contents on such third-party websites. Unless otherwise stated on the Website, the Company has no control over or rights in such third-party websites and is not responsible for their availability or security. If users access any linked third-party websites, they do so entirely at their own risk. The Company shall not be responsible for the contents of any third-party websites linked to the Website or any links contained in such third-party websites or any changes or updates to the above, and does not make any representations or warranties regarding the contents or accuracy of materials on such third-party websites. The Company shall not be responsible or liable for any loss or damage of any kind arising from or in connection with the use of the services or contents of such third-party websites. Further, any data or materials posted on the Website by any user may be viewed by users of other websites linked to the Website and the Company shall not be responsible for any improper use by any person other than the Company of any data or materials posted on the Website.
<h2><span style="text-decoration: underline;">6. Indemnity</span></h2>
Each user agrees to indemnify and hold harmless the Company and its associated companies, officers, directors, employees, agents, proprietors, partners, representatives, shareholders, servants, attorneys, predecessors, successors and assigns from and against any claims, actions, demands, injuries, liabilities, losses, damages, costs and expenses (including legal fees and litigation expenses on a full indemnity basis) (collectively "<strong>Losses</strong>") arising from or relating to the user's use of the Website or its contents or the user's breach of the <strong>Terms and Conditions</strong>, to the fullest extent permitted by applicable law. This indemnification shall be in addition to all other obligations of users under the <strong>Terms and Conditions</strong>, and shall not prejudice any other rights or remedies available at law to the Company.
<h2><span style="text-decoration: underline;">7. Disclaime</span>r</h2>
<b>TO THE FULLEST EXTENT PERMITTED BY APPLICABLE LAW, THE COMPANY AND ITS ASSOCIATED COMPANIES, OFFICERS, DIRECTORS, EMPLOYEES OR AGENTS SHALL NOT BE LIABLE IN ANY EVENT FOR DAMAGE OF ANY KIND SUFFERED BY ANY USERS WHATSOEVER DIRECTLY OR INDIRECTLY ARISING FROM OR RELATING TO SUCH USERS' USE OF OR INABILITY TO USE THE WEBSITE AND ITS CONTENTS, INCLUDING WITHOUT LIMITATION ANY ERRORS OR OMISSIONS IN SUCH CONTENTS, OR ANY DELETION, INCORRECT OR DELAYED TRANSMISSION OR LOSS OF ANY CONTENTS OR MATERIALS UPLOADED OR TRANSMITTED THROUGH THE WEBSITE.</b>
<h2><span style="text-decoration: underline;">8. Dealing with Advertisers</span></h2>
User's communication or business dealings with, or participation in promotions organized by, advertisers found on or through the Website, including payment and delivery of related goods or services, and any other terms, conditions, warranties or representations associated with such dealings, are solely between user and such advertiser. The Company shall not be responsible or liable for any loss or damage of any type or nature incurred as a result of any such dealings or as a result of the presence of the advertisers on the Website.
<h2><span style="text-decoration: underline;">9. Dealing with Other Users</span></h2>
While the Company uses its best endeavours to provide impartial job seeking and recruitment services, and represents a medium supporting information exchange between employers and employees, the Company will not be involved in dealings or disputes between Jobseeker and Employer and the Company shall not be responsible for the quality, security and legitimacy of the recruitment service. The Company does not warrant or guarantee the accuracy of the information and/or the resume provided by Jobseeker or of the recruitment advertisements provided by Employer. The Company does not guarantee that Employer will be able to pay the relevant remuneration or that Jobseeker will be competent to take the job offered by the Employer. Should any dispute arise between Employer and Jobseeker, Employer and Jobseeker shall resolve such disputes between themselves and the Company shall not be responsible for any such disputes.
<h2><span style="text-decoration: underline;">10. Limitation of Liability</span></h2>
Without prejudice to the above and subject to the applicable laws, the aggregate liability of the Company to any user for all claims arising from or relating to his/her use of the Company's services and the Website shall be limited to the fees received by the Company in respect of the service giving rise to such claims.
<h2><span style="text-decoration: underline;">11. Termination</span></h2>
In the event that any information provided by the user is inaccurate, in breach of any laws or contains indecent elements, the Company may instantly abrogate the user's account and membership without notice and reserves the right to take such action as it considers appropriate, desirable or necessary, including but not limited to taking legal action against such user. The Company reserves the right at any time to immediately terminate or suspend any user's account or access to the Website without notice, where the Company is of the opinion that the user has breached any of the <strong>Terms and Conditions</strong> or violated any law or regulations, and to take such further action as the Company in its sole discretion considers appropriate, desirable or necessary, including removing any material which it deems abusive, illegal, disruptive or inappropriate. The Company shall have the sole and absolute discretion to decide whether the user, Jobseeker or Employer has breached any of the <strong>Terms and Conditions</strong>, and such decision shall be final.
<h2><span style="text-decoration: underline;">12. Modification to Access or Website</span></h2>
The Company reserves the right at any time and from time to time to modify, change, suspend, discontinue or restrict: (a) users' access to, either temporarily or permanently, the Website (or any part thereof); or (b) the whole or any portion of this Website (and the services provided therein), with or without notice. The Company shall not be liable to users or to any third party for any such modification, change, suspension, discontinuation or restriction.
<h2><span style="text-decoration: underline;">13. Security Measures</span></h2>
The Company will use its reasonable endeavours to ensure that its officers, directors, employees, agents and/or contractors exercise prudence and due diligence in handling the personal data submitted by Jobseeker and that access to and processing of the personal data by such persons is on a "need-to-know" and "need-to-use" basis. The Company will use its reasonable endeavour to protect such personal data against any unauthorized or accidental access, processing or erasure.
<h2><span style="text-decoration: underline;">14. Governing Law and Jurisdiction</span></h2>
The Terms and Conditions and any dispute or matter arising from or incidental to the use of the Website shall be governed by and construed in accordance with the laws of Singapore. Any dispute, controversy or claim arising out of or in connection with the <strong>Terms and Conditions</strong>, including any question regarding its existence, validity, breach or termination, shall be referred to and finally resolved by arbitration in Singapore at the Singapore International Arbitration Centre ("<strong>SIAC</strong>") or at such other venue in Singapore as the parties concerned may agree in writing in accordance with the SIAC Rules. A tribunal shall consist of a single arbitrator to be appointed by the chairman of the SIAC. The decision of the tribunal shall be final and binding on the parties concerned. The language of the arbitration shall be English. The parties concerned undertake to keep the arbitration proceedings and all information, pleadings, documents, evidence and all matters relating thereto confidential. In the event of any breach of the <strong>Terms and Conditions</strong> by a party, the other party shall be entitled to remedies in law and equity as determined by arbitration.
<h2><span style="text-decoration: underline;">15. Entire Agreement</span></h2>
The <strong>Terms and Conditions</strong> shall constitute the entire agreement between user and the Company relating to his/her/its use of the Website, and shall replace and supersede all other communications (be it written or oral), discussions, letters and contracts relating to the subject matter hereof.
<h2><span style="text-decoration: underline;">16. Severability</span></h2>
The provisions of the <strong>Terms and Conditions</strong> shall be enforceable independently of one another and the validity of each provision shall not be affected if any of the others is invalid. In the event that any provision or part of a provision of the Terms and Conditions is determined to be or becomes illegal, invalid or unenforceable, the validity and enforceability of the remaining provisions or remaining part of the provision of the Terms and Conditions shall not be affected and, in lieu of such illegal, invalid, or unenforceable provision or part of a provision, there shall be added as part of the <strong>Terms and Conditions</strong> one or more provisions as similar in terms as may be legal, valid and enforceable under the applicable law.

</div>
<div class="span3"><?php include(Yii::app()->basePath . '/views/sidebar.php'); ?></div>
</div>